epochs: 100
batch_size: 16
label: cv   # cv, rog, tau
name: 'baseline'
debug: false

network:
  attn_heads: 20
  dropout: 0.15
  fc_layers: 2
  hidden_layers: 20
  hidden_size: 400

optim:
  lr: 1.0e-5

sch:
  factor: 0.1
  patience: 4
